version: '3.8'

services:
  servidor-vaijunto:
    build: .
    container_name: vaijunto_server
    ports:
      - "8080:8080"
    volumes:
      - ./caronas.json:/app/caronas.json
      - ./reservas.json:/app/reservas.json
      - ./usuarios.json:/app/usuarios.json
    